AWSTemplateFormatVersion: 2010-09-09
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        -
          Key: "Name"
          Value: "sunil-vpc"

  InternetGateway:
    Type: AWS::EC2::InternetGateway
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  SubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-west-2a
      CidrBlock: 10.0.1.0/24
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: true
  SubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-west-2b
      CidrBlock: 10.0.2.0/24
      VpcId: !Ref VPC

  RouteTablePublic:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
  InternetRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGateway
    Properties:
      RouteTableId: !Ref RouteTablePublic
      GatewayId: !Ref InternetGateway
      DestinationCidrBlock: 0.0.0.0/0

  RouteTablePrivate:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  SubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTablePublic
      SubnetId: !Ref SubnetA
  SubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTablePrivate
      SubnetId: !Ref SubnetB

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "Webserver Security"
      GroupDescription: "SSH,HTTP in and out"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 61.12.88.78/32
        -
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 61.12.88.78/32

      SecurityGroupEgress:
        IpProtocol: -1
        CidrIp: 0.0.0.0/0

  SecurityGroupDB:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "Database Security"
      GroupDescription: "SSH and MySQL in out"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 10.0.0.0/16
        -
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 10.0.0.0/16
        -
          IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 10.0.0.0/16

      SecurityGroupEgress:
        IpProtocol: -1
        CidrIp: 0.0.0.0/0

  Webserver:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-west-2a
      InstanceType: t2.micro
      ImageId: ami-28e07e50
      KeyName: suniloregonec2
      Tags:
        -
          Key: "Name"
          Value: "sunil.webserver"
        -
          Key: "Owner"
          Value: "sunil.surendran"
        -
          Key: "ExpirationDate"
          Value: "2018-06-20"
        -
          Key: "Project"
          Value: "Trainee"
        -
          Key: "Environment"
          Value: "Learning"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          curl -O https://bootstrap.pypa.io/get-pip.py
          yum install httpd -y
          echo "<h2>This is the webserver<h2>" > /var/www/html/index.html
          systemctl start httpd
          systemctl enable httpd
      NetworkInterfaces:
        -
          DeleteOnTermination: true
          AssociatePublicIpAddress: true
          Description: "Primary Network Interface"
          DeviceIndex: 0
          PrivateIpAddress: 10.0.1.10
          SubnetId: !Ref SubnetA
          GroupSet: !Ref SecurityGroup

  DatabaseServer:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-west-2b
      InstanceType: t2.micro
      ImageId: ami-28e07e50
      KeyName: suniloregonec2
      SecurityGroupIds:
        - !Ref SecurityGroupDB
      SubnetId: !Ref SubnetB
      Tags:
        -
          Key: "Name"
          Value: "sunil.database"
        -
          Key: "Owner"
          Value: "sunil.surendran"
        -
          Key: "ExpirationDate"
          Value: "2018-06-20"
        -
          Key: "Project"
          Value: "Trainee"
        -
          Key: "Environment"
          Value: "Learning"

